[supervisord]
nodaemon=true

[program:flask]
command=python3 app.py  # Flask tourne sur 8888
autostart=true
autorestart=true
stderr_logfile=/var/log/flask.err.log
stdout_logfile=/var/log/flask.out.log

[program:fastapi]
command=uvicorn main:app --port 9999 --host 0.0.0.0  # FastAPI tourne sur 9999
autostart=true
autorestart=true
stderr_logfile=/var/log/fastapi.err.log
stdout_logfile=/var/log/fastapi.out.log
